// [automatic generated by intermodule checker (imc) -- do not change ]
// 2017/10/17 15:37:06

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instanciated first
static int dummy = pearlrt::createSystemElements();

pearlrt::Device * d_stdout;	// philo.prl:8



namespace pearlrt {
   int createSystemElements() {

	// philo.prl:8
	static pearlrt::StdOut s_stdout;
	d_stdout = &s_stdout;

   return 0;
   }
}
